### PR TITLE
Running pdoc script with --all-submodules (an without --html) will pr…

### PR DESCRIPTION
**Pull request by sanseihappa**
…oduce a directory and .md files (similar to .html)

### CODE REVIEW

**Comment by BurntSushi** [comment]
Thanks!

**Comment by sanseihappa** [comment]
Sure! Thanks for the quick turnaround.  Are you planning a release to PyPI?

**Comment by BurntSushi** [comment]
`0.3.2` should be on PyPI with this PR! :-)

**Comment by sanseihappa** [comment]
Got it, thanks!

**Pull request merged**
